"""add_is_waiting_to_excel_tasks

Revision ID: 1de086eafcac
Revises: 3bff1c75f858
Create Date: 2026-02-11 17:49:56.743341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de086eafcac'
down_revision: Union[str, Sequence[str], None] = '3bff1c75f858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_waiting', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.drop_column('is_waiting')

    # ### end Alembic commands ###
