"""add current_row to excel_tasks

Revision ID: 3bff1c75f858
Revises: 7bb5b5826508
Create Date: 2026-02-11 16:50:38.099890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bff1c75f858'
down_revision: Union[str, Sequence[str], None] = '7bb5b5826508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_row', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.drop_column('current_row')

    # ### end Alembic commands ###
