"""reinit_migrations

Revision ID: 4a0ad49e2318
Revises: 
Create Date: 2026-02-13 16:37:07.332622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0ad49e2318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('excel_task_items', 'new_share_url',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Text(),
    #            existing_nullable=True)
    op.add_column('excel_tasks', sa.Column('target_channels', sa.JSON(), nullable=True))
    # op.alter_column('link_history', 'share_link',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.Text(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link_history', 'share_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('excel_tasks', 'target_channels')
    op.alter_column('excel_task_items', 'new_share_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
