"""add skip_count to excel_tasks

Revision ID: 7bb5b5826508
Revises: fe17b5b2158a
Create Date: 2026-02-11 16:10:47.866127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb5b5826508'
down_revision: Union[str, Sequence[str], None] = 'fe17b5b2158a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('interval_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('interval_max',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(10)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.alter_column('interval_max',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(10)'))
        batch_op.alter_column('interval_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.drop_column('skip_count')

    # ### end Alembic commands ###
