"""initial_schema

Revision ID: fe17b5b2158a
Revises: 
Create Date: 2026-02-11 11:03:44.494621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe17b5b2158a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.alter_column('interval_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('interval_max',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(10)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('excel_tasks', schema=None) as batch_op:
        batch_op.alter_column('interval_max',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(10)'))
        batch_op.alter_column('interval_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))

    # ### end Alembic commands ###
